[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "export-sentry-issue-mcp"
dynamic = ["version"]
description = "An MCP server for exporting Sentry issues to plain text files"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
keywords = ["sentry", "mcp", "model-context-protocol", "export"]
authors = [
  { name = "Jian-Long Huang", email = "contact@jlhuang.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: Implementation :: CPython",
]
dependencies = [
  "export-sentry-issue>=0.1.0",
  "fastmcp>=2.0.0",
  "requests>=2.31.0",
]

[project.urls]
Documentation = "https://github.com/jlhg/export-sentry-issue#readme"
Issues = "https://github.com/jlhg/export-sentry-issue/issues"
Source = "https://github.com/jlhg/export-sentry-issue"

[tool.hatch.version]
path = "src/export_sentry_issue_mcp/__about__.py"

[tool.hatch.build.targets.wheel]
packages = ["src/export_sentry_issue_mcp"]
core-metadata-version = "2.1"

[tool.hatch.build.targets.sdist]
core-metadata-version = "2.1"

[project.scripts]
export-sentry-issue-mcp = "export_sentry_issue_mcp.__main__:main"

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]

[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/export_sentry_issue_mcp}"
