[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "export-sentry-issue"
dynamic = ["version"]
description = "Export Sentry issues to plain text files for offline analysis and debugging"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
keywords = ["sentry", "export", "debugging", "error-tracking"]
authors = [
  { name = "Jian-Long Huang", email = "contact@jlhuang.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: Implementation :: CPython",
]
dependencies = [
  "requests>=2.31.0",
]

[project.urls]
Documentation = "https://github.com/jlhg/export-sentry-issue#readme"
Issues = "https://github.com/jlhg/export-sentry-issue/issues"
Source = "https://github.com/jlhg/export-sentry-issue"

[project.scripts]
export-sentry-issue = "export_sentry_issue.__main__:main"

[tool.hatch.version]
path = "src/export_sentry_issue/__about__.py"

[tool.hatch.build.targets.wheel]
packages = ["src/export_sentry_issue"]
core-metadata-version = "2.1"

[tool.hatch.build.targets.sdist]
core-metadata-version = "2.1"

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]

[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/export_sentry_issue}"
